name: CD

on:
  push:
    branches:
      - gh-pages
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image 
        run: |
          docker-compose build
          docker-compose exec -T mike deploy $(mike list)[0]