name: CD

on:
  push:
    branches:
      - gh-pages
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image 
        run: docker build . -t mkdocs-image -f Dockerfile
        run: docker container run -it mkdocs-image
        
      - name: do deploy comand on mike
        run: mike deploy $(mike list)[0]