name: CD

on:
  push:
    branches:
      - gh-pages
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build the Docker image 
        run: docker build . --file Dockerfile

      - name: do deploy comand on mike
        run: mike deploy $(mike list)[0]