name: CD

on:
  push:
    branches:
      - gh-pages
jobs:
  image-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image 
        run: docker build . --file Dockerfile

  deploy:
    steps:
      - uses: actions/checkout@v2
      
      - name: do deploy comand on mike
        run: mike deploy $(mike list)[0]