name: CD

on:
  push:
    branches:
      - gh-pages
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image 
        run: |
          docker build -t mkdocs-image
          docker run --name mkdocs-container -it mkdocs-image /bin/bash
          docker-compose ps -a
          docker container exec -it mkdocs-container bash
          mike deploy $(mike list)[0]
